"""empty message

Revision ID: 08f594b9bb34
Revises: 84d6b6e3b726
Create Date: 2020-04-01 16:25:54.159244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08f594b9bb34'
down_revision = '84d6b6e3b726'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
