"""empty message

Revision ID: 3fd37c520a39
Revises: 4bbc46c4a528
Create Date: 2020-03-29 18:28:29.847269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fd37c520a39'
down_revision = '4bbc46c4a528'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column(
        'genres', sa.ARRAY(sa.String(length=20)), nullable=True))
    op.add_column('Venue', sa.Column(
        'genres', sa.ARRAY(sa.String(length=20)), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    op.drop_column('Artist', 'genres')
    # ### end Alembic commands ###
